### ISSUE TITLE
How to use `from_args` and `std::env::args()`?

### ISSUE THREAD

**Issue by rise0chen** [DoumanAsh/arg.rs#1]
```rust
let mut args = std::env::args();
let _program_name = args.next().unwrap();
let args = ProgramArgs::from_args(args);
//let args = ProgramArgs::from_args(args.map(|arg| arg.as_str()));
```

**Comment by DoumanAsh** [comment]
So the problem is that it requires that your arguments live long enough.
The simplest approach to fix it would be to collect arguments into array/vec

For example:

```rust
use std::env;

#[derive(Args, Debug)]
///task-runner
///Task runner for admin server
pub struct Cli {
    #[arg(long, short)]
    ///Path to configuration file.
    pub config: task::cli::Config
}

impl Cli {
    pub fn new() -> Self {
        let args: Vec<String> = env::args().skip(1).collect();
        match Self::from_args(args.iter().map(String::as_str)) {
            Ok(args) => args,
            Err(arg::ParseError::HelpRequested(help)) => {
                println!("{}", help);
                std::process::exit(0);
            },
            Err(error) => {
                eprintln!("{}", error);
                std::process::exit(1);
            }
        }
    }
}
```

P.s. I probably forgot to document it, but `from_args` expects you to skip program name
P.s.s. Please note that the reason for this behavior is to hook up C style `main` arguments hence inconvenience. I'll consider adding shortcut function to parse arguments

**Comment by DoumanAsh** [comment]
You can try to check API that I've added https://github.com/DoumanAsh/arg.rs/commit/d42782df07a912802d0577d211776c2a0f99e77f

If you have API suggestions let me know

**Comment by rise0chen** [comment]
thanks

**Comment by DoumanAsh** [comment]
0.3.1 is released with `parse_args` function to simplify workflow for `std::end::args`
